### ISSUE TITLE
Add total result count?

### ISSUE THREAD

**Issue by sylvinus** [commonsearch/cosr-front#14]
Elasticsearch provides `TotalHits`, we could include it in the interface if we feel it adds value?

**Comment by hjacobs** [comment]
:+1: for adding total number of matching documents --- it could be displayed as a small grey number above or below the search results.

**Comment by chaconnewu** [comment]
PR sent https://github.com/commonsearch/cosr-front/pull/29

**Comment by sylvinus** [comment]
Fixed by @chaconnewu :)
