### ISSUE TITLE
Update installation instructions for first-time users of Docker

### ISSUE THREAD

**Issue by mewmew** [commonsearch/cosr-front#27]
When following the step-by-step [installation instructions](https://github.com/commonsearch/cosr-front/blob/master/INSTALL.md), the `make docker_pull` step fails, since the Docker daemon has not yet been started.

To make it easier for first-time users of Docker to jump straight in, add an additional step prior to the `make docker_pull` step, which describes how to start the Docker daemon.

The error reported if the Docker is not yet started is as follows.

```
u@x1 ~/g/s/g/c/cosr-front> make docker_pull
docker pull commonsearch/local-front
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Makefile:133: recipe for target 'docker_pull' failed
make: *** [docker_pull] Error 1
```

**Comment by chaconnewu** [comment]
Adding the following two steps before `make docker_pull` might solve the issue:
`
boot2docker up
`
and
`
eval "$(boot2docker shellinit)
`

**Comment by mewmew** [comment]
I don't have `boot2docker` on my system (using Arch Linux). However, starting the Docker daemon (i.e. `sudo systemctl start docker`) was enough to resolve this issue.

The only other issue is that since the Makefiles invoke `docker` directly without using `sudo`, the user would have to be added to the docker group (which may not be desirable in all cases, see [the Docker daemon attack surface article](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface)).

A potential solution to this issue is to create an alias for `docker` as described in [this article](http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/).

```
alias docker="sudo /usr/bin/docker"
```

**Comment by mewmew** [comment]
Note that the installation instructions for [Arch Linux](https://docs.docker.com/engine/installation/linux/archlinux/) solved all of these issues except the one regarding the `docker` group.

I'd suggest adding a note regarding docker security to the installation instructions, and perhaps suggest that adding an alias for docker as described above is one possible solution.

**Comment by mewmew** [comment]
From https://github.com/commonsearch/cosr-front/pull/28#issuecomment-196429886

> This pull request was sent out prematurely. It turns out that aliases are ignored by make, or rather only used by interactive terminal environments. In either case, the described solution does not fix the initial problem.

**Comment by mewmew** [comment]
If anyone has an alternative solution to mitigate the security implications of adding your user to the `docker` group, please let us know.

The suggested `docker` alias (see pull request [#27](https://github.com/commonsearch/cosr-front/pull/28/files#diff-7d442b7eb49f5fc377f51e74b291cfc1R24)) turned out not to work in combination with `make`.

**Comment by mewmew** [comment]
Close the issue for now as it has remained inactive for more than 6 months.

Anyone with further insight into the current status of this issue, may re-open it or add comments of the current progress.
