### ISSUE TITLE
Keep language in logo link

### ISSUE THREAD

**Issue by sylvinus** [commonsearch/cosr-front#7]
Because we don't use cookies, language detection is a bit fragile.

Currently clicking on the logo loses the selected language, it would be great to keep the `?g=fr` parameter in the link.

This needs to be done both in JS and in the Go template.

**Comment by chaconnewu** [comment]
I attempted this issue with this PR: https://github.com/commonsearch/cosr-front/pull/32

The idea is to return to the "full" layout, clear all search related states and timeouts, and use window.history.pushState to append the language info. Please take a look.
